blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('' , views.post_list , name= 'post_list'),
    # path('' , views.PostListView.as_view() , name= 'post_list'),
    path('tag/<slug:tag_slug>', views.post_list , name= 'post_list_by_tag' ),
    path('<slug:slug>-<int:year>-<int:month>-<int:day>' , views.post_detail , name= 'post_detail'),
    path('<int:post_id>/share/' , views.post_share , name= 'post_share'),
    path('<int:post_id>/comment/' , views.post_comment , name= 'post_comment'),
    path('search/' , views.post_search , name= 'post_search'),


]

mysite/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/' , include ('blog.urls' , namespace= 'blog')),
    path('accounts/' , include ('account.urls' , namespace= 'account')),

]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
                      .filter(status = Post.Status.PUBLISHED)



class Post (models.Model):
    class Status(models.TextChoices):
        DRAFT = ('DF' , 'Draft')
        PUBLISHED = ('PB' , 'Published')

    title = models.CharField(max_length = 250)
    slug = models.SlugField(max_length = 250 , unique_for_date = 'publish')
    author = models.ForeignKey(User , on_delete = models.CASCADE , related_name = 'blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default = timezone.now)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)
    status = models.CharField(max_length = 2 , choices = Status.choices , default = Status.DRAFT)
    

    tags = TaggableManager()

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ['-publish' ]
        indexes = [models.Index(fields= ['-publish'])]

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.slug, self.publish.year,
                                                 self.publish.month, self.publish.day])
    
    
    def __str__(self):
        return self.title
    


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE , related_name= 'comments')
    name = models.CharField(max_length = 50)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)
    active = models.BooleanField(default= True)

    class Meta:
        ordering = ['created']
        indexes = [models.Index(fields=['created'])]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField( max_length= 30)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required= False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']
        # exclude = ['created', 'updated', 'active']

class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count
#from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.postgres.search import TrigramSimilarity
from django.contrib.auth.decorators import login_required
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm


# Create your views here.

class PostListView(ListView):
    #model = Post
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    
    paginator = Paginator(post_list, 2)
    page_number = request.GET.get('page' , 1)
    
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)


    return render(request,
                  'blog/post/list.html', {'posts' : posts , 'tag': tag}
                  )

@login_required
def post_detail(request , slug, year, month, day):
    post = get_object_or_404(Post, status = Post.Status.PUBLISHED,
                             slug = slug, publish__year = year,
                             publish__month = month , publish__day = day
                             )
    
    comments = post.comments.filter(active=True)
    form = CommentForm

    post_tags_ids = post.tags.values_list('id' , flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
                                    .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                    .order_by('-same_tags' , '-publish')[:3]    


    # try:
    #     post = Post.published.get(id = id)
    # except Post.DoesNotExist:
    #     raise Http404('No Post Found')

    return render (request, 'blog/post/detail.html',
                    {'post' : post , 'comments': comments , 
                     'form': form , 'similar_posts': similar_posts},
                  )


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"""Read {post.title} at {post_url}


                        {cd['name']}'s comment: {cd['comments']}
                        """
            send_mail(subject, message, 'admin@admin.com' , [cd['to']])
            sent = True
    elif request.method == 'GET':
        form = EmailPostForm()
    return render (request, 'blog/post/share.html' , {'post': post , 'form': form , 'sent': sent})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment= form.save(commit=False)
        comment.post = post
        comment.save()
    return render(request, 'blog/post/comment.html', {'post': post, 'form': form, 'comment': comment})


def post_search(request):
    form = SearchForm
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.published.annotate(similarity=TrigramSimilarity('title', query))\
                                    .filter(similarity__gt=0.1).order_by('-similarity')

            # results = Post.published.annotate(search=SearchVector('title', 'body'))\
            #                         .filter(search=query)


            # search_vector = SearchVector('title' , weight='A') + SearchVector('body' , weight='B')
            # search_query = SearchQuery(query)
            # results = Post.published.annotate(search=search_vector , 
            #                                   rank=SearchRank(search_vector, search_query))\
            #                                   .filter(rank__gte=0.3).order_by('-rank')


    return render (request , "blog/post/search.html" , 
                       {'form': form , 'query': query , 'results': results})

blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %}
    Add a Comment 
{% endblock title %}


{% block content %}
    {% if comment %}
        <h2> Your Comment Has Been Added </h2>
        <p> 
            <a href="{{ post.get_absolute_url }}">
                Back to the Post
            </a>
        </p>
    {% else %}
        {% include "blog/post/includes/comment_form.html" %}
    {% endif %}
{% endblock content %}

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content%}
    <h1>
        {{ post.title }}
    </h1>
    <p class = "date">
        Published {{ post.publish }} by {{ post.author }}
    </p>

    <p>
        {{ post.body }}
    </p>


    <div class="tags"> 
        {% for tag in post.tags.all %}
            <a href= "{% url "blog:post_list_by_tag" tag.slug %}">
                #{{tag.name}}
            </a>
            {% if not forloop.last %} , {% endif %}
        {% endfor %}
    </div>
    <p>
        <a href='{% url "blog:post_share" post.id %}'>
            Share This Post
        </a>
    </p>

    <h2> Similar Posts </h2>
    {% for similar_post in similar_posts %}
        <p>
            <a href="{{ similar_post.get_absolute_url }}">
                {{ similar_post.title }}
            </a>
        </p>
    {% empty %}
        There Are No Similar Posts Yet
    {% endfor %}

    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment {{ total_comments|pluralize }}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class=comment>
            <p class=info> 
                Comment by {{ comment.name }}
                {{ comment.created }}
            </p>
            <p>
                {{ comment.body }}
            </p>
        </div>
    {% empty %}
        <p> There Are No Comments </p>    
    {% endfor %}
    {% include "blog/post/includes/comment_form.html" %}
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}
    My Blog
{% endblock %}

{% block content %}
    <h1> My Blog </h1>
    {% if tag %}
        Posts Tagged with "{{ tag.name }}"
    {% endif %}
    {%for post in posts%}
        <h2>
            <a href= "{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <p class="tags">
            Tags:
                {% for tag in post.tags.all %}
                    <a href= "{% url "blog:post_list_by_tag" tag.slug %}">
                        {{tag.name}}
                    </a>
                    {% if not forloop.last %} , {% endif %}
                {% endfor %}
        </p>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        <p>
            {{ post.body|truncatewords:30 }}
        </p>
    {%endfor%}

    {% include "pagination.html" with page=posts %}

{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% block title %}
    Search
{% endblock title %}
    

{% block content %}
    {% if query %}
        <h1> Search results for {{ query }} </h1> 
        <h3>
            {% with results.count as total_results %}
                {{ total_results }} results {{ total_results|pluralize }}           
            {% endwith %}
        </h3>  
        {% for post in results %}
            <h3>
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a>
            </h3>
            <p>
                {{ post.body|truncatewords:10 }}
            </p>
        {% empty %}
            <p>
                There Are No Results.
            </p>
        {% endfor %}

        <p>
            <a href="{%  url "blog:post_search" %}">
                Search Again
            </a>
        </p>
    {% else %}
            <form method="get">
                {{ form.as_p}}
                <input type="submit" value="search"> 
            </form>
    {% endif %}
{% endblock content %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}
    Share a Post
{% endblock title %}


{% block content %}
    {% if sent %}
        <h3> Email Sent Successfully! </h3>
        <p> "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }} </p>
    
    {% else %}
        <h1> Share "{{ post.title }}" by Email </h1>
        <form method= 'post'>
            {{ form.as_p }}
            {% csrf_token %}
            <input type= 'submit' , value = 'Send Email' />
        </form>
    {% endif %}
{% endblock content %}